# Generated by Django 5.1.6 on 2025-02-11 13:20

import modules.file_upload_module
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_main_image',
            field=models.ImageField(upload_to=modules.file_upload_module.FileUploader.upload_to, verbose_name='عکس کاور مقاله'),
        ),
        migrations.AlterField(
            model_name='bloggallary',
            name='blog_image',
            field=models.ImageField(upload_to=modules.file_upload_module.FileUploader.upload_to, verbose_name='عکس مقاله'),
        ),
    ]
