# Generated by Django 4.1.4 on 2023-06-03 17:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "user_name",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="نام کاربری"
                    ),
                ),
                (
                    "mobile_number",
                    models.CharField(
                        blank=True,
                        max_length=11,
                        null=True,
                        verbose_name="شماره موبایل",
                    ),
                ),
                (
                    "user_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("teacher", "معلم"),
                            ("student", "دانش آموز"),
                            ("visitor", "کاربر عادی"),
                            ("superuser", "سوپر یوزر"),
                            ("admin", "ادمین"),
                        ],
                        default="visitor",
                        max_length=50,
                        null=True,
                        verbose_name="نوع کاربر",
                    ),
                ),
                (
                    "register_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="تاریخ ثبت نام"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="وضعیت کاربر"),
                ),
                (
                    "active_code",
                    models.CharField(
                        blank=True,
                        default=0,
                        max_length=100,
                        null=True,
                        verbose_name="کد فعال سازی",
                    ),
                ),
                (
                    "is_admin",
                    models.BooleanField(default=False, verbose_name="وضعیت ادمینی"),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "کاربر",
                "verbose_name_plural": "کاربران",
            },
        ),
    ]
