# Generated by Django 4.1.4 on 2023-06-03 19:43

from django.db import migrations, models
import modules.file_upload_module


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_customuservisitordetail_customuserteacherdetail_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuserstudentdetail",
            name="age",
            field=models.PositiveIntegerField(
                blank=True, default=0, null=True, verbose_name="سن"
            ),
        ),
        migrations.AddField(
            model_name="customuserstudentdetail",
            name="father_name",
            field=models.CharField(blank=True, max_length=50, verbose_name="نام پدر"),
        ),
        migrations.AddField(
            model_name="customuserstudentdetail",
            name="user_class",
            field=models.CharField(
                blank=True,
                choices=[
                    ("C1-1R", "اول دبیرستان رشته ریاضی کد اول"),
                    ("C1-2R", "اول دبیرستان رشته ریاضی کد دوم"),
                    ("C1-1E", "اول دبیرستان رشته انسانی کد اول"),
                    ("C1-2E", "اول دبیرستان رشته انسانی کد دوم"),
                    ("C1-1T", "اول دبیرستان رشته تجربی کد اول"),
                    ("C1-2T", "اول دبیرستان رشته تجربی کد دوم"),
                    ("C2-1R", "دوم دبیرستان رشته ریاضی کد اول"),
                    ("C2-2R", "دوم دبیرستان رشته ریاضی کد دوم"),
                    ("C2-1T", "دوم دبیرستان رشته تجربی کد اول"),
                    ("C2-2T", "دوم دبیرستان رشته تجربی کد دوم"),
                    ("C2-1E", "دوم دبیرستان رشته انسانی کد اول"),
                    ("C2-2E", "دوم دبیرستان رشته انسانی کد دوم"),
                    ("C3-1R", "سوم دبیرستان رشته ریاضی کد اول"),
                    ("C3-2R", "سوم دبیرستان رشته ریاضی کد دوم"),
                    ("C3-1T", "سوم دبیرستان رشته تجربی کد اول"),
                    ("C3-2T", "سوم دبیرستان رشته تجربی کد دوم"),
                    ("C3-1E", "سوم دبیرستان رشته انسانی کد اول"),
                    ("C3-2E", "سوم دبیرستان رشته انسانی کد دوم"),
                    ("C4-R", "پیش دانشگاهی رشته ریاضی"),
                    ("C4-T", "پیش دانشگاهی رشته تجربی"),
                    ("C4-E", "پیش دانشگاهی رشته انسانی"),
                ],
                max_length=20,
                null=True,
                verbose_name="مقطع تحصیلی",
            ),
        ),
        migrations.AlterField(
            model_name="customuserstudentdetail",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=modules.file_upload_module.FileUploader.upload_to,
                verbose_name="عکس کاربر",
            ),
        ),
        migrations.AlterField(
            model_name="customuserteacherdetail",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=modules.file_upload_module.FileUploader.upload_to,
                verbose_name="عکس کاربر",
            ),
        ),
    ]
