# Generated by Django 4.1.4 on 2023-06-03 20:06

from django.db import migrations, models
import modules.file_upload_module


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_customuserstudentdetail_age_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuserstudentdetail",
            name="born_date",
            field=models.DateField(blank=True, null=True, verbose_name="تاریخ تولد"),
        ),
        migrations.AddField(
            model_name="customuserstudentdetail",
            name="identity_number",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="شماره شناسنامه"
            ),
        ),
        migrations.AddField(
            model_name="customuserstudentdetail",
            name="place_born",
            field=models.CharField(blank=True, max_length=50, verbose_name="محل تولد"),
        ),
        migrations.AddField(
            model_name="customuserstudentdetail",
            name="previous_avg",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=4,
                null=True,
                verbose_name="معدل مقطع قبل",
            ),
        ),
        migrations.AddField(
            model_name="customuserstudentdetail",
            name="user_special_situation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("normal", "نرمال"),
                    ("miltary_inj", "فرزند جانباز"),
                    ("miltary", "فرزند نظامی"),
                    ("teach_fal", "فرزند فرهنگی"),
                    ("illness", "بیماری خاص"),
                    ("intelligance", "نخبه"),
                ],
                default="normal",
                max_length=50,
                null=True,
                verbose_name="شرایط خاص",
            ),
        ),
        migrations.AddField(
            model_name="customuserteacherdetail",
            name="user_slug",
            field=models.SlugField(blank=True, null=True, verbose_name="شناسه کاربر"),
        ),
        migrations.AlterField(
            model_name="customuserstudentdetail",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=modules.file_upload_module.FileUploader.upload_to,
                verbose_name="عکس کاربر",
            ),
        ),
        migrations.AlterField(
            model_name="customuserteacherdetail",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=modules.file_upload_module.FileUploader.upload_to,
                verbose_name="عکس کاربر",
            ),
        ),
    ]
