# Generated by Django 4.1.4 on 2023-06-03 20:15

from django.db import migrations, models
import modules.file_upload_module


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_customuserstudentdetail_born_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("teacher", "معلم"),
                    ("student", "دانش آموز"),
                    ("visitor", "کاربر عادی"),
                    ("superuser", "سوپر یوزر"),
                    ("admin_post", "ادمین مقالات"),
                    ("admin_exam", "ادمین امتحانات"),
                    ("admin_regi", "ادمین ثبت نام"),
                    ("writer", "نویسنده"),
                ],
                default="visitor",
                max_length=50,
                null=True,
                verbose_name="نوع کاربر",
            ),
        ),
        migrations.AlterField(
            model_name="customuserstudentdetail",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=modules.file_upload_module.FileUploader.upload_to,
                verbose_name="عکس کاربر",
            ),
        ),
        migrations.AlterField(
            model_name="customuserteacherdetail",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=modules.file_upload_module.FileUploader.upload_to,
                verbose_name="عکس کاربر",
            ),
        ),
    ]
