# Generated by Django 4.1.4 on 2023-06-09 17:08

from django.db import migrations, models
import modules.file_upload_module


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0006_alter_customuserstudentdetail_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuserstudentdetail",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=modules.file_upload_module.FileUploader.upload_to,
                verbose_name="عکس کاربر",
            ),
        ),
        migrations.AlterField(
            model_name="customuserteacherdetail",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=modules.file_upload_module.FileUploader.upload_to,
                verbose_name="عکس کاربر",
            ),
        ),
    ]
