# Generated by Django 5.1.6 on 2025-02-11 13:20

import modules.file_upload_module
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_customuserstudentdetail_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuserstudentdetail',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=modules.file_upload_module.FileUploader.upload_to, verbose_name='عکس کاربر'),
        ),
        migrations.AlterField(
            model_name='customuserteacherdetail',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=modules.file_upload_module.FileUploader.upload_to, verbose_name='عکس کاربر'),
        ),
    ]
